const AUTHENTICATION_REQUEST = "AUTHENTICATION_REQUEST";
const AUTHENTICATED = "AUTHENTICATED";
const NOT_AUTHENTICATED = "NOT_AUTHENTICATED";
const LOGING_OUT = "LOGING_OUT";
const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";

const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
const REGISTER_USER_REQUEST_SUCCESS = "REGISTER_USER_REQUEST_SUCCESS";
const REGISTER_USER_REQUEST_FAILURE = "REGISTER_USER_REQUEST_FAILURE";

export {
  AUTHENTICATION_REQUEST,
  AUTHENTICATED,
  NOT_AUTHENTICATED,
  LOGING_OUT,
  GET_PROFILE_REQUEST,
  GET_PROFILE_SUCCESS,
  GET_PROFILE_FAILURE,
  REGISTER_USER_REQUEST,
  REGISTER_USER_REQUEST_SUCCESS,
  REGISTER_USER_REQUEST_FAILURE,
};
