const GET_QUOTES_REQUEST = "GET_QUOTES_REQUEST";
const GET_QUOTES_REQUEST_SUCCESS = "GET_QUOTES_REQUEST_SUCCESS";
const GET_QUOTES_REQUEST_FAILURE = "GET_QUOTES_REQUEST_FAILURE";


export {
  GET_QUOTES_REQUEST,
  GET_QUOTES_REQUEST_SUCCESS,
  GET_QUOTES_REQUEST_FAILURE,
};
