const GET_QUOTES_REQUEST = "GET_QUOTES_REQUEST";
const GET_QUOTES_REQUEST_SUCCESS = "GET_QUOTES_REQUEST_SUCCESS";
const GET_QUOTES_REQUEST_FAILURE = "GET_QUOTES_REQUEST_FAILURE";

const LIKE_QUOTE_REQUEST = "LIKE_QUOTE_REQUEST";
const LIKE_QUOTE_REQUEST_SUCCESS = "LIKE_QUOTE_REQUEST_SUCCESS";
const LIKE_QUOTE_REQUEST_FAILURE = "LIKE_QUOTE_REQUEST_FAILURE";

const ADD_QUOTE_REQUEST = "ADD_QUOTE_REQUEST";
const ADD_QUOTE_REQUEST_SUCCESS = "ADD_QUOTE_REQUEST_SUCCESS";
const ADD_QUOTE_REQUEST_FAILURE = "ADD_QUOTE_REQUEST_FAILURE";

const DELETE_QUOTE_REQUEST = "DELETE_QUOTE_REQUEST";
const DELETE_QUOTE_REQUEST_SUCCESS = "DELETE_QUOTE_REQUEST_SUCCESS";
const DELETE_QUOTE_REQUEST_FAILURE = "DELETE_QUOTE_REQUEST_FAILURE";

export {
  GET_QUOTES_REQUEST,
  GET_QUOTES_REQUEST_SUCCESS,
  GET_QUOTES_REQUEST_FAILURE,
  LIKE_QUOTE_REQUEST,
  LIKE_QUOTE_REQUEST_SUCCESS,
  LIKE_QUOTE_REQUEST_FAILURE,
  ADD_QUOTE_REQUEST,
  ADD_QUOTE_REQUEST_SUCCESS,
  ADD_QUOTE_REQUEST_FAILURE,
  DELETE_QUOTE_REQUEST,
  DELETE_QUOTE_REQUEST_SUCCESS,
  DELETE_QUOTE_REQUEST_FAILURE,
};
