const GET_QUOTES_REQUEST = "GET_QUOTES_REQUEST";
const GET_QUOTES_REQUEST_SUCCESS = "GET_QUOTES_REQUEST_SUCCESS";
const GET_QUOTES_REQUEST_FAILURE = "GET_QUOTES_REQUEST_FAILURE";

const LIKE_QUOTE_REQUEST = "LIKE_QUOTE_REQUEST";
const LIKE_QUOTE_REQUEST_SUCCESS = "LIKE_QUOTE_REQUEST_SUCCESS";
const LIKE_QUOTE_REQUEST_FAILURE = "LIKE_QUOTE_REQUEST_FAILURE";

export {
  GET_QUOTES_REQUEST,
  GET_QUOTES_REQUEST_SUCCESS,
  GET_QUOTES_REQUEST_FAILURE,
  LIKE_QUOTE_REQUEST,
  LIKE_QUOTE_REQUEST_SUCCESS,
  LIKE_QUOTE_REQUEST_FAILURE,
};
